### ISSUE TITLE
Is there equivalent to register of threepenny?

### ISSUE THREAD

**Issue by MarisaKirisame** [reflex-frp/reflex#169]
So I had successfully created an event, but I want to add a hook so that whenever that event fire, an IO () is run.

Basically this https://hackage.haskell.org/package/threepenny-gui-0.8.2.1/docs/Reactive-Threepenny.html#v:register

**Comment by NCrashed** [comment]
Hi, you can use `performEvent_`:

```
performEvent_ $ ffor e $ \value -> liftIO $ myIOFunc value
```

Where `e :: Event t a `

сб, 24 февр. 2018 г. в 16:30, 雾雨魔理沙 <notifications@github.com>:

**Comment by MarisaKirisame** [comment]
How can I get the result in IO? I dont know what PerformEvent is out there... I only see tons of monad transformer 😢 
Thx in advance!

**Comment by ali-abrar** [comment]
@MarisaKirisame Given `f :: a -> IO b` and `e :: Event t a` you can do:

```
result :: Event t b <- performEvent $ fmap (liftIO . f) e
```
Whenever `e` fires, the event will be performed and the `result` event will fire with the value that was computed by `f`.

> How can I get the result in IO? 

Do you mean you want the result to be `IO b` instead of `Event t b`? If that's the case, you could do something like write to an MVar or something from within the `performEvent`. However, most of the time you don't need that. If you need to do more IO with the value, you could just use another performEvent. If, e.g., you wanted to use `putStrLn`, you could do `performEvent_ $ fmap (liftIO . putStrLn . show) result`.

**Comment by MarisaKirisame** [comment]
Got it, thx
