### ISSUE TITLE
listViewWithKey inside dyn issue

### ISSUE THREAD

**Issue by dfordivam** [reflex-frp/reflex#170]
Not sure if this is an issue, but it does look like a strange behaviour

              ev <- dyn $ (\tc -> listViewWithKey ((f tc) <$> dynV) (g tc)) <$> textContent

In this code I have Dynamic `textContent` which influences both the `Dynamic t (Map k v)` and the `(k -> Dynamic t v -> m (Event t a))`. So it was a natural for me to put it above `listViewWithKey`

But when I put `traceShow` in `f`, I saw that it is being computed for all the versions of `textContent`.
ie if `textContent` has changed 4 times, and then `dynV` changes, the `f` is computed 4 times, for all the values of `textContent`. In my case this caused an Array out of bound access exception, so I caught it.

This works fine..

              ev <- listViewWithKey ((f <$> textContent <*> dynV) (g textContent))

I think something wrong is going on here...

**Comment by ryantrinkle** [comment]
@dfordivam That sounds like the expected behavior: `dyn` recomputes its entire contents whenever the input changes.  For this reason, it's usually a good idea to push uses of `Dynamic`s as far "down" into your widgets as possible.

**Comment by dfordivam** [comment]
@ryantrinkle I think I was not clear in my explanation.

lets say `textContent` changes from `Array (0,1) ..` to Array (0,2) ..` over time

Similarly the value of `dynV` changes from some value withing range of (0,1) to (0,2)

But the `dynV` is derived in some ways from `textContent` so its value will always be in the valid range.

So the `f` should never raise an out of bounds exception, right?

**Comment by ryantrinkle** [comment]
Ah, I see.  This is where things get dicey!  Even though a `Dynamic` is no longer being used, its updates will still propagate until the GC detects that it's unused and cleans it up.

It may be possible to add some kind of error handling to Reflex to delay the error, possibly long enough that it never occurs because the GC gets rid of it first.  However, this would probably be quite tricky to do without a performance impact.

Is it possible to refactor your code to avoid using partial functions entirely?

**Comment by dfordivam** [comment]
Yeah I kind of figured out this from the trace prints.. but this was hard to believe ..
And I have already refactored code and got rid of `dyn`
I am not sure what further to do with this issue... perhaps I will close this for now..
