### ISSUE TITLE
CMV: Event is Applicative/Monad 

### ISSUE THREAD

**Issue by alexfmpe** [reflex-frp/reflex#280]
I think there could be a `pure :: a -> Event t a`, similar to [ZipList](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#t:ZipList)'s `pure x = ZipList (repeat x)`, by having it *always* fire.

That is, fire **whenever any non-pure event** fires.
If all events (including the ones inside `Dynamic`s) are `pure`/`never`, then the `pure` ones are also `never`.

We already have `Apply` and `Bind` meaning 'parallel' and 'nested' intersection for `Event`, so that'd give us `Applicative` and `Monad`.

Let's look at the laws...

#### Left identity: `unit ** v ≅ v`
The LHS fires at least as much as the RHS side, and `<*>` makes the result fire whenever both arguments fire, which in this case means exactly as often as the RHS side, which means 
`unit ** v = fmap ((),) v ≅ v`

#### Right identity: `u ** unit ≅ u`
`coerce leftIdentity`

#### Associativity: `u ** (v ** w) ≅ (u ** v) ** w`
LHS & RHS will fire exactly when `u`, `v,` `w` simultaneously fire (intersection is associative, more news at eleven), and differ only in how the tuples are nested

#### Left identity: `return >=> g  =  g`
```haskell
return >=> g
= \x -> return x >>= g
= \x -> join $ fmap g (return x)
= \x -> coincidence $ fmap g (return x)
= \x -> g x
= g
```
`coincidence $ fmap g (return x)` will fire exactly when both
1. `return x` fires with payload `x`
1. `g x` fires
Since 2 implies 1, this is exactly `g x`

#### Right identity: `g >=> return  =  g`
```haskell
g >=> return
= \x -> coincidence $ fmap return (g x)
= \x -> g x
= g
```
`coincidence $ fmap return (g x)` will fire exactly when both
1. `g x` fires with payload `y`
1. `return y` fires
Since 1 implies 2, this is exactly `g x`

#### Associativity: `(g >=> h) >=> k = g >=> (h >=> k)`
In both cases, the resulting event will fire exactly when both
1. `g x` fired with payload `y`
1. `h y` fired with payload `z`
1. `k z` fired

This just in, intersection still associative

**Comment by Ericson2314** [comment]
But it's possible to count every time an event fires, which would leak the global state of reflex into every event.

I think what we want instead is either:

1. some sort of nicer thing on `holdDyn Nothing . fmap Just` thing such that you use the Dynamic applicative / monad and then do `fmapMaybe id . updated` to get out.

2. A sum type which is either a behavior or dynamic, which is a Monad just as Dynamic is.

1 becomes more interesting if we mess with `MaybeDyn` and a hypothetical one-shot event so as to get a `OneShotEvent (Dynamic a)` as the final result.

**Comment by cgibbard** [comment]
There are a few different reasons why having an Event which fires whenever
any other Event does is not a great plan - it's an interesting idea to
think about, but it breaks a few of the principles we learned early on in
constructing FRP systems.

1. It's impure. The meaning of such an Event is affected by unrelated parts
of the program. You can write a seemingly pure function, and if it involves
such an Event, now some other part of the program which starts a timer or
does some network communication causes your Event to fire more often, and
changes its meaning.

2. One of the key properties of pure functions in reflex is the following:
output Events only fire at a subset of the times that the input Events do
(with values that are a pure function of the current values of Behaviors,
and the values of presently-firing Events). This is very important for
performance reasons. You can think of an Event as granting permission to
its recipient to cause computation to occur whenever it fires. When none of
its input Events are firing, a reflex computation can not do any work, and
so costs nothing in terms of time. Expensive computations can be safely
granted only input events that fire infrequently. Cheap computations in the
same system can be granted high-frequency events. Also, holds can only
change their value when an input Event is firing, and so caches become less
effective the more often their input Event fires. Keeping spurious firings
to a minimum is important for that reason.

Related to this kind of thing are operations which delay Events
infinitesimally, or by some fixed amount. We have the latter in reflex, but
as impure functions, and they're carefully designed to skip occurrences if
the system is lagging. We specifically eschew the infinitesimal delays
entirely, because they make it far too easy to write programs that just
freeze up or fall farther and farther behind.

I'd also question where this sort of operation that obtains an Event which
is firing whenever any other Event is firing would have been useful and
meaningful in a real world setting -- it seems like an unlikely thing to
really want, which would make the corresponding Applicative and Monad
instances a bit of a trap.

**Comment by ElvishJerricco** [comment]
Your description of `pure x :: Event t X` sounds like `Behavior t X`. Maybe behaviors are just the limit of events as the occurrence rate approaches infinity? :P

**Comment by ryantrinkle** [comment]
It's not possible to implement an event that "always" fires (and, even if you could, it would be a bad idea).  Cale's notes pretty well summed it up.  Best-case scenario, you'll be forcing "pull" performance characteristics *everywhere* - and that's a really bad scenario.
