### ISSUE TITLE
Can `now :: PushM t (Event t ())` be implemented?

### ISSUE THREAD

**Issue by parenthetical** [reflex-frp/reflex#414]
I might be overlooking something, but does Reflex have a way to get an event occurrence at the current moment, e.g. through a value `now :: PushM t (Event t ())`? I'm asking mostly out of curiosity, although it might make what I'm working on  much simpler.

It is possible to get at it within `push` and then write a Reflex wrapper to have it available in every inner PushM, but that would leave the outer expression hanging:
```
pushWithNow :: (Reflex t)
            => (a -> Event t () -> PushM t (Maybe b))
            -> Event t a
            -> Event t b
pushWithNow f e = push (\a -> do
                           hE <- headE e
                           f a (() <$ hE))
                  e
```

**Comment by ryantrinkle** [comment]
That seems like a very reasonable idea, and it should even admit a more efficient implementation than headE - in particular, you should never need to collect subscribers, because the event is known to be firing right away.

Would you like to take a stab at implementing it?  I think it will not be too bad, but I'm happy to support as necessary.

**Comment by parenthetical** [comment]
I gave it a go in pull request #416 

Maybe there should also be a function `occurrence :: Event a -> PushM (Maybe a)`?
That would subsume `coincidence` with `push occurrence` (unless that messes with GC?), and it might avoid some awkward uses of alignEventWithMaybe.
It would also have the nice property of `occurrence =<< now   =   pure (Just ())`
