### ISSUE TITLE
joinE missing

### ISSUE THREAD

**Issue by paolino** [reflex-frp/reflex#49]
I propose a joinE combinator for flattening events out of dyn, even it's provided from DOM it's a Reflex only code to solve it

joinE
  :: (Reflex t, MonadHold t f) =>
     Event t (Event t a) -> f (Event t a)
joinE = fmap switch . hold never

**Comment by ryantrinkle** [comment]
This looks like a very useful function, but I'd be a bit concerned about the name, since it doesn't follow the laws that Monad's `join` is expected to follow.  Do you have any other ideas about what we could call it?

**Comment by cgibbard** [comment]
Perhaps switchE. We have switchPromptlyDyn and probably switchDyn = switch
. current ought to be a thing as well, just for the sake of discoverability.

We'd then have that return . switch . current = return . switchDyn =
switchE . updated.

(Of course switchE does an additional hold here that isn't needed when you
start from a Dynamic already.)

**Comment by mightybyte** [comment]
I have also wanted functions like this.  These kinds of things were not at all obvious to me when I was starting out.  But I think we should include several of the common nested-dyn and nested-event patterns.  It would probably be good to enumerate them all at once and try to come up with a coherent naming scheme.

**Comment by ryantrinkle** [comment]
Yes, I agree about switchDyn.  However, switchDyn /= switchE . updated - it has the initial 'never' component rather than starting with the current thing in the Dynamic.

**Comment by cgibbard** [comment]
Oh you're right.

**Comment by paolino** [comment]
From a simpler user pov  join is referred to the operational signature, so
here we have 2 different symbol interpretations.  I suggest in general a
community naming renaming effort.
Imo, joinE is stating (with the E) that Event t is NOT a monad, which is an
additional information.
Btw, silly question, why it is not a monad?

This looks like a very useful function, but I'd be a bit concerned about
the name, since it doesn't follow the laws that Monad's join is expected to
follow. Do you have any other ideas about what we could call it?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/reflex-frp/reflex/issues/49#issuecomment-216554129>

**Comment by Saulzar** [comment]
Previously I've been using a switch typeclass for things which can be
switched, I called it 'switching' only because of naming scarcity.

class Reflex t => Switching t r whereSource
    switching :: MonadHold t m => r -> Event t r -> m r

Very useful for all the variety of complex datatypes which can be switched,
from simple things like Switch (Event (Event a)), Switch a => Switch (a,
a), to much more complex things like Html builder types. I think it's
possible to provide good laws surrounding such a typeclass, and it avoids
the massive proliferation of naming.

Probably two, Switch and SwitchPromptly, as the semantics are different.

**Comment by Saulzar** [comment]
I should add, mind you - that this is more like 'switchAndHold' rather than
what we currently call switch - but this is similar to what Paolo was
suggesting.

**Comment by Saulzar** [comment]
I don't think Event can be a Monad - for instance how do you implement `return`?

**Comment by paolino** [comment]
Ok, I see it's Behavior the Monad around. Forget it.

**Comment by ryantrinkle** [comment]
What does everyone think of this?

```haskell
switchEvent :: (Reflex t, MonadHold t m) => Event t a -> Event t (Event t a) -> m (Event t a)
```

**Comment by mightybyte** [comment]
@ryantrinkle That seems reasonable.  Like I mentioned above, I think I'd much rather see a systematic enumeration of all the possibilities at once rather than just building them up haphazardly one here, another there, etc.  It would be cool if they could all be unified into a type class kind of like @Saulzar showed.  But maybe that's not doable, I don't know...

Here's a Google Sheet to get things started:

https://docs.google.com/spreadsheets/d/1hZsOXd904lhPzCWzf1Ux9s1GHaeIBZg3rahRlJaC1Gk/edit?usp=sharing

**Comment by luigy** [comment]
`switchEvent` landed as `switchHold` for which `joinE` becomes `switchHold never`
