### ISSUE TITLE
heightBagRemove error

### ISSUE THREAD

**Issue by barakber** [reflex-frp/reflex#71]
I'm trying to create a Navigation/Router in Reflex.
I'm using a `Dynamic t State` that I want to read and update recursively while I move between pages (every page should be able to use and update that `State`).
The code builds (with commit 50d298cb1b5ed850ec017e2aab10ffa1fb5466b0), but fails with an error:

``` haskell
main :: MonadWidget t m => m ()
main = do
    rec
        dRoute  <- value <$> textInput def
        dPage   <- mapDyn (router dState) dRoute
        eWidget <- dyn dPage
        dWidget <- holdDyn (constDyn def) eWidget
        let dState = joinDyn dWidget
        display dState
    return()
    where
        router :: MonadWidget t m => Dynamic t State -> Text -> m (Dynamic t State)
        router dState "Page1" = text "Hello from Page1" >> return dState
        router dState _       = text "Otherwise" >> return dState
```

the error:
heightBagRemove: Height 1 not present in bag HeightBag {_heightBag_size = 2, _heightBag_contents = fromList [(0,1)]}
CallStack (from HasCallStack):
  error, called at src/Reflex/Spider/Internal.hs:637:14 in reflex-0.5.0-CudEVeFTJAH8ajDdcbYxWR:Reflex.Spider.Internal

Is there a better way? am I abusing the rec-do notation?

**Comment by ryantrinkle** [comment]
@barakber Sorry for the slow reply!

The issue here is that once `eWidget` fires, a cycle is created.  Specifically, `eWidget` will replace `dWidget`'s contents with `dState`, which is defined in terms of `dWidget` itself.  This creates a causality paradox: now, whenever `dState` changes, it will cause `dState` to change.  (`eWidget` will also cause `dState` to change, but that isn't a problem.)
